### ISSUE TITLE
Bad result

### ISSUE THREAD

**Issue by Programmerwyl** [JorgeGIlG/MTF_Estimator#10]
Hi JorgeGIlG

By comparing with imatest, Sometimes, it will get poor results. Do you know why? Imatest and code use the same image and select the same area

The original image is
![9999](https://user-images.githubusercontent.com/22095854/107114313-de15ee00-689f-11eb-92cd-dd5bb510fe6e.png)

imatest result:

![9999_YT 27_01_sfr](https://user-images.githubusercontent.com/22095854/107114316-ea01b000-689f-11eb-82c3-c88ba986b388.png)

code result:

![image](https://user-images.githubusercontent.com/22095854/107114342-161d3100-68a0-11eb-99fc-d5102c0e07fd.png)

thanks

**Comment by JorgeGIlG** [comment]
Hi Programmerwyl

The algorithm was designed to work with satellite images. It should also provide good results from regular cameras so I'm glad to have your feedback. Let's see if we can work it out. Let me suggest a few ideas:

**1-.** Imatest has a lot of features and options that sometimes can be confusing. At the end of mtf_estimator.py there is commented code:

```
angle="16.776550" 
fwhm="2.101313"
imgFile = "/ram/myedge_angle_"+str(angle)+"_fwhm_"+str(fwhm)+".tif"
edge = Edge(imgFile, np.float64(fwhm), cols=500, rows=100, angle=np.float64(angle))
ImageFile = imgFile
```
from which you can create quasi-perfect edge tiff images. From there you can play with Imatest parameters to get an idea on how it behaves with those synthetic edges.

**2-.** Your image has three bands (RGB). FidMTF only measures the first one: `band = ds.GetRasterBand(1)` in readImage. Yoy may want to check the other two.

**3-.** If you are not using the QGIS plugin then you are probably cutting the image for FidMTF. Please make sure the software you use doesn't apply any kind of resampling or lossy compression to the image.

**4-.** As it was designed for low quality targets FidMTF expects a lot of samples (long edges). Try to use the longest possible edge.

![image](https://user-images.githubusercontent.com/67840250/107150044-2266c400-695c-11eb-9008-e5054184cb1f.png)

It will likely yield better results:

![image](https://user-images.githubusercontent.com/67840250/107150103-6d80d700-695c-11eb-9be3-6c675e831c9d.png)

If you are interested in MTF measurements we can also discuss about the pros and cons of the ISO 12233 binning approach that Imatest uses vs. optimization techniques.

Regards

**Comment by Programmerwyl** [comment]
Hi JorgeGIlG:

thank you very much  for you advice.
According to your suggestions I will make more attempts and update if there is new progress

Regards

**Comment by JorgeGIlG** [comment]
Hi Programmerwyl:

Did you get satisfactory results? I want to be sure that the software is useful. Is there a way I can cooperate with you further?
