### ISSUE TITLE
a question about the code of calculating the MTF

### ISSUE THREAD

**Issue by Walaahij** [JorgeGIlG/MTF_Estimator#24]
Hello Jorge:
How are you?

can I ask about the code of the calculating the MTF at Nyquist ?

thanks in advance
Walaa

**Comment by Walaahij** [comment]
Hello Gorge
I want to ask about the code of the calculations of MTF
https://github.com/JorgeGIlG/MTF_Estimator
I want to know what is the units of the number of the MTF@Nyquist ? 

because I was asked to change the code and define the length of the pixel of the camera we are using so we can have
the Nyquist number in [Cycle/pixel]

I went through the code but I think the code doesn't define the unit of the MTF@Nyquist, also the axises of the graph, doesn't say anything about the units.

I can send you the part of the code that says about what I needed

**Comment by JorgeGIlG** [comment]
Hi Walaa.

Yes. I should add axis labels. 
All frequencies in this tool are in cycles per pixel.

**Comment by Walaahij** [comment]
and do we have to define the pixel's length? is it different for each camera? or it doesn't matter which camera we are using?

**Comment by Walaahij** [comment]
Thanks

**Comment by JorgeGIlG** [comment]
You need at least two samples to capture the highest frequency (Nyquist freq is 0.5 cycles per sample). If you sample with pixels then the pixels set the limit. Then you may use other units (e.g. lines/mm, if you know the pixel size)

**Comment by ilyak93** [comment]
@JorgeGIlG, Hi, getting back to this issue, looking at this table of interpretations:

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/b86df4aa-ffba-4813-9cb7-00b5d819c9dd)

and the code:

```
# If needed, remove the last element of the PSF to get an even number of elements
        if lsf.shape[1]/2. != lsf.shape[1]//2.:
            lsf = lsf[:, :-1]

        sampFreq = np.float64(lsf.shape[1])/(np.max(lsf[0])-np.min(lsf[0]))

        lsf = lsf[1]
        tmp = lsf
        tmp = tmp / np.sum(tmp)
        #self.console('Nyquist resolution Jorge calculated in line pairs per millimeter (lp/mm)', round(max(lsf), 2))
        n = lsf.shape[0]

        lsf = np.append(np.append(np.zeros([20*n]), lsf), np.zeros([20*n]))

        lsf = lsf/np.sum(lsf)
        n = np.float64(lsf.shape[0])
        mtf = np.fft.rfft(lsf)
        mtfFreq = np.linspace(0, 0.5*sampFreq, num=mtf.shape[0], dtype=np.float64)

        mtfVsFreq = interpolate.interp1d(mtfFreq, np.absolute(mtf), kind='linear')
        freqVsMtf = interpolate.interp1d(np.absolute(mtf), mtfFreq, kind='linear')
```

Does this mean, that I only need to multiply `mtfFreq` by `2/pixel size` to get the mtf with x-axis of line-pairs / mm?

**Comment by JorgeGIlG** [comment]
Hi @ilyak93,

No. The distace units are always pixels. Please, take a look to the _rfft_ documentation for details about how to handle frequencies.
