### ISSUE TITLE
a shift to a common origin

### ISSUE THREAD

**Issue by ilyak93** [JorgeGIlG/MTF_Estimator#25]
Hello, Jorge, thanks a lot for your work, it is very useful. 

My question is about the operation in the code  which you describe in your algorithm as a shift to a common origin. 

in the script [mtf_estimator_algorithm.py](https://github.com/JorgeGIlG/MTF_Estimator/blob/devel/qgis_plugin/mtf_estimator/mtf_estimator_algorithm.py) in line 340:

`esfData = np.sort(esfData, axis=1)`

You are sorting the esfData by axis=1 which means sorting the values at each row, where the first row corresponds to the concatenation of the X - EdgeSubPx_i (where X are just the indices 0 to width of the raws and EdgeSubPx_i is the computed value of the edge after the linear regression for each row) and the second row corresponds to the actual values of the edge for each row corrected by a, b coefficients from the sigmoid fit, also concatenated. 

So I get the fact it is kind of a shift to a common origin (sorting the shifted indices), although what is a little bit awkward for me is that the sort is also done on the corrected Y values, thus in the sorted values there isn't anymore any correspondence between the appropriate shifted index of each pixel to the corrected value of the pixel. I.e before the sort for each index j in row i, Y_i[j] was the corresponding value in the image of the edge to the X[j] - EdgeSubPx_i[j] corrected index. 

I don't fully understand why it is correct to sort the Y values (corrected by a,b coeffs) and why this operation is allowed and doesn't break the correctness of the step to get the ESF and derive from it the LSF. 

After that i see in the code in the function `calcOptimizedLsf` :
```         
def costFunc(params):
        smooth, ga, gb, gc, gw = params
        lsfRep = interpolate.splrep(x, y, k=3, s=smooth)
        psfSpline = interpolate.splev(xAux, lsfRep, der=1)
        return np.sum(np.abs(psfSpline - gaussianFunc(xAux, ga, gb, gc, gw)))

x = esfData[0]
y = esfData[1]
```

x and y are simply those sorted values, and in the optimization solver each time the represented with spline of k=3 followed by the derivation to get the psf to approximate the Gaussian to it. So I understand what happens at this point, and the whole code that performs the previously described steps of the algorithm, only the semantics of that sort aren't clear to me.

I.e i saw another much simpler and coarse implementation where a preprocessing interpolation is done to the image using the angle of the edge to rotate the object and the edge (which is a very coarse and noisy operation which eliminates the angle to 0)  and then all the rows summed to one row (columns-wise) and compute the derivative of that row, that is another way, maybe less complicated but probably less correct. 

If you could explain this moment, ill be thankful, also provide any papers that you followed by implementing this particular method, which could spread some light on this sorting operation and its correctness.

Thank you in advance.

**Comment by JorgeGIlG** [comment]
Hi Ilya,

Thank you for your feedback. You are right. It doesn't make sense because it is a bug.
That part of the code creates an oversampled ESF my shifting multiple transects to a common origin, the estimated sub-pixel position of the edge, and merging them. Then the edge values are sorted in increasing X axis order. The _sort_ function, as you have spotted, has the unintended effect of sorting all rows independently. I've already fixed that using _argsort_.

I developed this algorithm from scratch. It is not based on any paper. I've been postponing writing one for years. I hope someone will eventually write a review about the different algorithms that are out there, including this one.

**Comment by ilyak93** [comment]
@JorgeGIlG, thanks for the fast reply. 

Its not related directly to the issue, but could you check the algorithm for a particular input after that insight about the sort operation.

This change doesn't effect significantly for the input of the chessboard I took from you repository, i.e this one:

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/5508636a-9a5e-47a9-a0c8-16b207ae2752)

but effects more significantly on my input [image](https://ibb.co/D5dVG6b).

The ESF estimation actually doesn't look too bad, but I wonder why the LSF look very messy for this input, also the bigger the area of the edge I take, the more noisy LSF I get.

Could you take a look please and tell me for your opinion do that figures make sense for the algorithm as you know it:

big area selection of the edge:

![big_area](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/9b904d46-e4dd-425f-ad6c-63e3b8d9cfe2)

![big_area_enlarged](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/a678db92-40e3-4525-ac46-62a749b506a2)

![big_area_ESF_LSF](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/1cf718cc-78ff-4432-8b36-9a831461cfee)

![big_area_all](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/d1322132-3125-4f53-8304-3ed317c0055b)

small area selection of the edge:

![small_area](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/d7af9a90-4d71-4027-b05d-4106012ae508)

![small_area_enlarged](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/6e79e213-733d-4ef0-a0ff-1f05b36a7bfb)

![small_area_ESF_LSF](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/c3c890b3-842c-42a9-bcfd-2baa2b9b2e92)

![small_area_ESF_LSF](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/2dade2ba-4780-48fe-ae5c-9af095a64124)

**Comment by ilyak93** [comment]
Well, i've also tested it on the original image, the one I mentioned in the beginning of the recent response.

It looks like the correct sorting operation introduce some noise, which is naturally comes with the sorting operation (the correct one).

I'm wondering if the solution to this, if anything needed to be resolved or corrected  here at all, is some smoothing to the ESF. Kinda making me think about the differences depending on the input.

**Comment by ilyak93** [comment]
@JorgeGIlG, the FWHM looks a bit large, I used the code from the master branch (the one with the smoothing factor corrected to 1e-5). Should it be so big for this synthetic image ? I'm not aware of the synthesizing method nor the expected result of the algorithm on the image, just saw it was previously around 2 px.

![orig_newest_updated](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/98387c35-6fb8-425c-96ab-275bbf76a850)

**Comment by ilyak93** [comment]
@JorgeGIlG, when its seems correct (if i chose the edge more or less symmetrically like here and the FWHM looks fine) the estimated Gaussian seems to not fit well as much as I understand, correct me if I'm wrong. 
![corrected_full](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/bf73ca2f-2494-47d4-9b85-6d49f598bc37)

**Comment by JorgeGIlG** [comment]
@ilyak93 The algorithm requires some care when choosing the areas or it may become numerically unstable. The warnings and a PSF that doesn't look like a PSF are hints that something is going wrong. The figures are there for you to evaluate that.
These are the results I get from your image.
![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/67840250/d3c5d5fa-fd09-4507-8558-49233e6b1866)

**Comment by ilyak93** [comment]
@JorgeGIlG, thanks a lot, that actually looks much better. Can you add please also the brown curve in your plot (the Gaussian fit) jsut for the complicity of the issue here. That's great news.

**Comment by JorgeGIlG** [comment]
@ilyak93 At line ~412 you will find commented plots. Please serve yourself enabling and disabling them.
The one you are interested in is:

`self.SubPlot[0,1].plot(xAux, gaussianFunc(xAux, ga, gb, gc, gw),"-", color="brown")`

**Comment by ilyak93** [comment]
@JorgeGIlG, I'm jsut not familiar with QGIS so I don't know how you chose that polygon in such convenient way. Tried through this hour to manage it, but without any success so far.  The selection that I see here is from QGIS right ?

**Comment by JorgeGIlG** [comment]
@ilyak93 Yes. It is from QGIS. Note that you can dowload the plugin as a [zip file](https://plugins.qgis.org/plugins/mtf_estimator/) edit whatever you need inside and install it on QGIS. The current version is 1.3.1, released today.
There is an example on how to draw a polygon in the section _[Obtaining Successful Results](https://jorgegilg.github.io/MTF_Estimator/)_ 
If you continue having trouble please come back to me.

**Comment by ilyak93** [comment]
@JorgeGIlG, in the new version of QGIS the interface a bit different and my silly struggle is to choose the polygon. It just doesn't finish it when I double click or press 'Enter', that's a really silly one. I tried to install the old QGIS 3.10, but it should be installed from the sources and the compilation fails some why, that's another headache.

**Comment by JorgeGIlG** [comment]
Try right click to finish creating the polygon.

27 Nov 2023, 16:42 by ***@***.***:

**Comment by ilyak93** [comment]
@JorgeGIlG , when I do that the selection disappear but it write  in the notifications on the bottom of the window on left "0 feature(s) selected on layer layer_name".

**Comment by ilyak93** [comment]
@JorgeGIlG, by the way, when you choose a polygon with such angle like you chose for the for my input (just as an example), do you know if the input to your script first preprocessed with some interpolation ? 

I think it is a valid point to think about for anyone who want to use your algorithm without the QGIS selection functionality.
Because I've used some simple selection by a regular rectangle, but I assumed that the selection you showed, i.e a symmetrical one, doing better, but I was wondering if it is due to an interpolation which the QGIS does automatically to create an input suitable for the following computations.

**Comment by JorgeGIlG** [comment]
Hi Ilya. No. No interpolation is performed. Never.

By the way. In the repository root there is a Jupyter notebook sample that you can use to run the algorithm outside QGIS. If the image is not georeferenced, like your case, the polygon can be defined using pixel coordinates.

27 Nov 2023, 17:51 by ***@***.***:

**Comment by ilyak93** [comment]
@JorgeGIlG, hi, thanks for the idea.
What is the order of the points of the polygon in sense of first pair of coordinates first left top point, second pair top right, third pair bottom right and forth pair bottom left, is that it ? 
I don't need the fifth in the case like you chose the angled polygon right ?

```
Polygon ((29.32538932146828614 -37.22900444938820641, 
83.82494438264737369 -52.0925194660734121, 
90.31298665183538787 -25.78645717463848186, 
25.66849276974415517 -9.27144048943269894, 
29.32538932146828614 -37.22900444938820641))
```

Trying to avoid trying all the combinations :)

**Comment by JorgeGIlG** [comment]
Try these:

`Aoi_Wkt = '''
Polygon ((
587 -175,
620 -185,
585 -296,
552 -285,
587 -175
))
'''`

They are pixel coordinates, where the origin is the top left corner.

**Comment by JorgeGIlG** [comment]
Yes

27 Nov 2023, 20:39 by ***@***.***:

**Comment by JorgeGIlG** [comment]
I don't like the _smooth_ value you get. It is part of the optimization but it is not being optimized. It should start with the minimum value, but that is the maximum.
Do you have
`        starting_smooth_val = 1e-5`
on line 381?

**Comment by ilyak93** [comment]
@JorgeGIlG, yes. 

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/9a93edd6-ed4e-4ed5-9cb5-f51e014ee19c)

**Comment by JorgeGIlG** [comment]
It is good to have feedback from users. It shouldn't be so difficult to get good results. Let me review the code to see if there is a way to make it more robust. Suggestions are welcome.

**Comment by ilyak93** [comment]
@JorgeGIlG, I appreciate your assistance. I'll try to figure it out as well.

**Comment by ilyak93** [comment]
@JorgeGIlG, hi. Running the algorithm on many polygon of different width and height along the edge and seeing that the smooth factor always go to the max value of the boundaries, also visually seeing that the data after the corrected argsort is much more noisy then obviously the sorted data which didn't introduce any noise, makes me think that for better results on such high resolution image the smooth factor seems to be likely bigger, those will be my next experiments. 

What do you think about it theoretically? Let's day that in the extreme case, the smoothing factor will be so big, that we will almost represent the esf as the sigmoid best fitting to it, how will it influence the whole algorithm? 

I just wondered also why not to dedicated the sigmoid function directly, I guess the reason is to be loyal to the original data and rely on it and not on the sigmoid of it? 


What do you think about that?

**Comment by JorgeGIlG** [comment]
Hi @ilyak93. You are right. I would like to estimate the MTF of the original data with noise removed. Working directly with the fitted Sigmoid doesn't add much value, I think.
The tricky part is to find a smoothing parameter that keeps the spline loyal, as you say, to the original data while avoiding falling into overfitting, which is the problem we are facing.
According to the documentation finding the proper smoothing factor is a matter of _trial and error_. There might be a way to find a reasonably good smoothing factor automatically, I am testing finding it via optimization, again, using the RMSE with the fitted sigmoid as the cost function.

**Comment by ilyak93** [comment]
Hi @JorgeGIlG, long story short, there a lot of interesting point to investigate through this approach, but one thing is relatively working according also to those last discussions, is to enlarge the high boundary of the smooth factor during the optimization (gaining the LSF).

The higher the resolution of the edge (the more transects taken, the more noise introduced into the spline representation and thus into it's derivative the LSF), the harder the problem is, which is a wide-common issue when applying machine learning algorithms, particularly optimizations and fittings, which work good on low resolution and therefore on low dimensional spaces, to high dimensional ones. 

This transition for my opinion can be non-trivial at all, depends on the quality of results and accuracy that is wanted.

The most high-level solution on the level of decision making is for example to sub-sample the high-resolution edge with low-resolutions images, this also gives some results which look reasonable:

![Untitled](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/45d88a4e-b23a-4ee3-bebb-3883e98d1ad1)

But not very practical, if we want to sample the whole edge.

The other solution is the one related to the smoothing. And here I want to closely show and examine the result I've obtained:

![Untitled](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/04643064-f523-4ea4-91c7-6390525c3abe)

As it can be seen, the smooth factor is relatively big but does it represent the data with noise removed ?

Lets zoom in on few spots:

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/4d3775f7-022c-48f3-a0bb-09a2f1170773)

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/f855460a-dc0f-47f3-9eca-ebe76be73d02)

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/489baf4d-62f1-47fb-8243-98ad061ac16c)

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/cbb4c152-ca1e-4244-9ce6-1f87fdc54aa7)

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/f54f778a-cca0-4d94-858b-7b69f03e3195)


Legend: blue `x` - data points, black - fitted sigmoid

They do differ.

The previously though about derivation of the sigmoid directly came from that situation when the smooth factor becomes large, so the red estimation is not that far from the black. So it does look like an issue of choice how to deal with the general issue of representing the noisy ESF which was gotten in the super sample approach and deriving it to obtain the LSF (with noise that also largely depends on the noise in the ESF or its representation), and get the PSF by fitting the best Gaussian to the LSF (with some noise).

What do you think, is it valuable to derive the ESF spline with this smoothing ? 
There is still some difference in the FWHM, a whole 1 pixel (at the most, one result in the small sample is also 4), so it hard a bit to tell how accurate the results are.

Next, I think it will be a good idea to create high resolution synthetic edges and try to achieve expected results and maybe with some high-resolution and frequent noise.

**Comment by JorgeGIlG** [comment]
Hi @ilyak93. Good analysis. Thank you.
I've decided to simplify and split the problem. Now the optimization is done in two stages. The first fits the sigmoid to the oversampled ESF and the second attempts to find a good smoothing factor for the ESF spline model with k=1, which is more numerically robust. The Gaussian is no longer used for the optimization. Following the original idea, the oversampled edge is then modelled by a smoothed spline (k=3), taking the smoothing factor from k=1, and the MTF is calculated on its derivative.
Please note that there is a class _Edge_ that creates synthetic edges. The file [data/myedge_angle_16.776550_fwhm_2.101313.tif](https://github.com/JorgeGIlG/MTF_Estimator/blob/master/data/myedge_angle_16.776550_fwhm_2.101313.tif) was created this way. There is an example on how to use it [here](https://github.com/JorgeGIlG/MTF_Estimator/blob/3b3805b9c7f114ae76a96d6b22f2928df6f286a7/qgis_plugin/mtf_estimator/mtf_estimator_algorithm.py#L451).

If you want you can try this version ([mtf_estimator-1.4.0RC1.zip](https://github.com/JorgeGIlG/MTF_Estimator/files/13516970/mtf_estimator-1.4.0RC1.zip)), from where I expect you to obtain better results than the ones you've got in your previous comment.

**Comment by ilyak93** [comment]
Hi, @JorgeGIlG. Later I'll give a more full feedback on the results with this changes, for now I've just ran few times and indeed for some selections which previously where problematic, it manages to handle it. 


Correct me if Im wrong about the theoretical basis of this update, the sigmoid of the oversampled esf is a model of our step-function, which would be ideal step-function in an ideal world.

But we may say it is a too much over simplification of our data which has noise that introduced by the optics and other possible factors, so we want only use this model to approximate our data in other representation, i.e the spline one, thus this adds another level of modeling (making it more complex), which preserves the behavior patterns of the real data, but also optimized in matter to fit our prime model of the edge, which says that the edge is a step-function in the ideal case. 

So it's kind of a prime and secondary modeling, is that a sensible way to look at it? 

Deriving only the sigmoid, i.e using in this terms only the prime model may be oversimplification and over reduction, right? 


There is another matter, no related to our recent discussions, but came up in some brain-storming with my lab-engineer. 

After the linear regression of the subEdgePx, correct me if I'm wrong on this, the current implementation doesn't re interpolate the transects (before merging into a super sample) but only shifts the indices (0 to max_width) by the refined subEdgePx. 

What we thought is maybe the indices of each transect also should first interpolated, because subEdgePx changed a bit, I mean if we refine the edge pixel, why not go another step forward and then first refine the x axis of each of the transects and then do the sort to get the super sampled esf. 

It sounds to me a validate operation, and I might guess it wouldn't introduce any significant change to the results produced by the current method. 

A think, if it is valid, then it just a refinement of the current method, but not a radical one.

I'll be glad your opinion to join this brain-storm. we may try it ourselves, but maybe you will find it efficient for your release as well :)

**Comment by ilyak93** [comment]
So for such choice of edge as bellow the results are as previous and the optimized smoothing factor is the maximal :
![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/aea27c70-168d-43a7-971a-42cc46792996)

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/32248939-8980-4132-904f-15e1da4e460f)

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/e32cc3c4-2836-42c5-bada-2b019419e98f)

As you can see the smoothing as previously is not enough.

for smaller selection (approximately half of the full size) it does work:

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/0efb15cd-751a-44cd-a84f-b82679e0e788)

although for wider choice : 
![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/f1878450-f1e2-4bae-8d3e-ccda6e961889)

its enough for the spline representation to have some not significant waves and the lsf become very not similiar to a gaussian, thus the result isn't very truthful : 
![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/f1d8a565-14bd-4283-9762-1e4eaf3ba4be)

But generally for narrow selections of half of the length of the moon it works:

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/2abaf3c6-edaf-4d0a-8092-435bfefdc8bd)


If I set the smoothing optimization boundary to 5.0 the smoothing required satisfied and it works also for the longer selections:

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/8b2aabd6-2707-4e88-a431-514956a6d4d9)

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/0e927b5a-6e4b-4e5a-b5fe-0b61b3102791)


For the record I do think spiting the optimization is a good idea, because with possible bigger smoothing, the simultaneous optimization can converge to local minima, because it will find local minimal smoothing for which it also will find a very fitting gauusian (and it is a little bit ambiguous, do we want the best fitting of the gaussian or the best smoothing factor for which a gaussian can be fitted, so there are many minimas there I think), so in the current approach the sigmoid is the indication for the best smooth (from the understanding I got and described in the previous response).  

About the Gaussian optimization, it could for example be efficient in the image where i took half of the moon with a wide selection, because the LSF does resemble to a Gaussian but yet is very noisy, so Gaussian fitting can handle those cases.  

Do you think this smoothing values are valid for the selection of the whole moon edge length ?

Thank you in advance.

**Comment by JorgeGIlG** [comment]
Hi @ilyak93. Yes and yes, but I would explain it slightly differently.
I think that the sigmoid is limited representing the behavior of a real sensor. A more capable mathematical model would be a polynomial or, as it is the case, a piecewise polynomial, although there is a trade-off. The sigmoid is very robust while the spline is sensitive to noise.
Now the approach is to try to obtain the best of both models. Once we have the oversampled ESF (real data) we [build a spline from it](https://github.com/JorgeGIlG/MTF_Estimator/blob/d284594fd8e8f3e940afd95401d447a2775eb4b0/qgis_plugin/mtf_estimator/mtf_estimator_algorithm.py#L368). The tricky part is to obtain the smoothing factor. For that, and only for that in the ESF modelling,  [a sigmoid is used](https://github.com/JorgeGIlG/MTF_Estimator/blob/d284594fd8e8f3e940afd95401d447a2775eb4b0/qgis_plugin/mtf_estimator/mtf_estimator_algorithm.py#L334). So if you think that we are somehow forcing the model to behave as a sigmoid you are right, but it is limited to the smoothing factor, the heavy lifting is done by the spline representation.

This approach is also used in the _Transect_ class, where the data is fitted to a sigmoid just to determine the subpixel position of the edge.


> Hi, @JorgeGIlG. Later I'll give a more full feedback on the results with this changes, for now I've just ran few times and indeed for some selections which previously where problematic, it manages to handle it (although for some selections I think I had to enlarge the smooth factor again, I want to make a more ful analysis).
> 
> Correct me if Im wrong about the theoretical basis of this update, the sigmoid of the oversampled esf is a model of our step-function, which would be ideal step-function in an ideal world.
> 
> But we may say it is a too much over simplification of our data which has noise that introduced by the optics and other possible factors, so we want only use this model to approximate our data in other representation, i.e the spline one, thus this adds another level of modeling (making it more complex), which preserves the behavior patterns of the real data, but also optimized in matter to fit our prime model of the edge, which says that the edge is a step-function in the ideal case.
> 
> So it's kind of a prime and secondary modeling (thus we get an intermediate approximation constrained by the noisy pattern of our real world and the model of the ideal scenario) , is that a sensible way to look at it?
> 
> Deriving only the sigmoid in the hypothetical scenario compared to the current one, i.e using in this terms only the prime model may be oversimplification and over reduction, right?

Hi @ilyak93. Yes and yes, but I would explain it slightly differently.
I think that the sigmoid is limited representing the behavior of a real sensor. A more capable mathematical model would be a polynomial or, as it is the case, a piecewise polynomial, although there is a trade-off. The sigmoid is very robust while the spline is sensitive to noise.
Now the approach is to try to obtain the best of both models. Once we have the oversampled ESF (real data) we [build a spline from it](https://github.com/JorgeGIlG/MTF_Estimator/blob/d284594fd8e8f3e940afd95401d447a2775eb4b0/qgis_plugin/mtf_estimator/mtf_estimator_algorithm.py#L368). The tricky part is to obtain the smoothing factor. For that, and only for that in the ESF modelling,  [a sigmoid is used](https://github.com/JorgeGIlG/MTF_Estimator/blob/d284594fd8e8f3e940afd95401d447a2775eb4b0/qgis_plugin/mtf_estimator/mtf_estimator_algorithm.py#L334). So if you think that we are somehow forcing the model to behave as a sigmoid you are right, but it is limited to the smoothing factor, the heavy lifting is done by the spline representation.

This approach is also used in the _Transect_ class, where the data is fitted to a sigmoid just to determine the subpixel position of the edge.

**Comment by ilyak93** [comment]
Thanks @JorgeGIlG for your perspective. Those are good notions, indeed it's only for getting a smooth factor which in this way in some sense inspired by the sigmoid robustness. 

I'm not sure you saw the second post with the results, probably you posted an answer just when I posted the results. 

Do you think the answer, as it is showed in the last results, enlarging upper bound of the optimization for the smooth factor and getting bigger smooth? 

It makes me starting to wonder about previous steps and the wellness and correctness of the process of the creation of the over sampled ESF, particularly the outlier remove for estimating the refined edgeSubPx or even the whole refinement, interesting to check the ablation of this steps. 

There was also a point I though about, but eventually convinced myself that it seems the algorithm currently does the right thing when it only refines the edgeSubPx without reinterpolating the x axes of each transect.

But does that level of noise look reasonable to you? 

Well, first I must try the synthesis of the edges but also with some normal noise. 

But it's a bit awkward that the bigger the choice of the edge polygon, the bigger the magnitude of the noise and thus the smoothing factor. I would expect the smoothing factor maybe to change a bit, but not that significantly.

**Comment by JorgeGIlG** [comment]
Hi @ilyak93. Regarding the figures you posted. You can set the thresholds you like, not in vain the documentation says that it is a matter of _trial and error_. Just make sure that the spline (red) fits reasonably well to the data. To do so, as you have been doing, It may be necessary to try different polygons.
I am about to release a version which includes the basin-hopping algorithm to attempt to evade local minima. It is much slower, though.

**Comment by ilyak93** [comment]
Hi, @JorgeGIlG, thanks. 

> BTW. I've noticed that my sample has a different resolution than yours, so the results will differ.

That's really awkward, if I download it, it seems that the resolution do preserves. Maybe you downloaded it in another format ?
The "save as" default give me a png format. I did the same check for the previous upload to the external storing resource (its not available anymore anyways).

Let me try with another [image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/8d4be50b-1d3f-48b8-a0e5-fcb05aeeb99e) directly through github.

I downloaded the file and compared, they look exactly the same, including the resolution:

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/6cdb82d7-9420-4216-9727-7ab35f2d839b)

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/2c51a9a2-cca8-479a-8d25-fc9f6d503f01)

> I think there is no need to interpolate. The Transect class find the sub-pixel position of the inflection point of the sigmoid, which is where the perfect edge position is supposed to be for each row. That point becomes then the x axis origin for all rows, which allows the creation of the oversampled edge. Intuitively, the DN values of the near pixels determine the sub-pixel shift to one side or the other.

I see it likewise, thanks.

> Yes. The edge neighborhood is not that uniform

You are totally right, now that I also looked at the enhanced image with all of the noise, thank you for that insight. 
We will try to improve the setup to reduce the noise in the data collection stage.

The previous results were a bit confusing, here are the results with the new version that you sent:

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/2ed3dc23-e036-488d-b3eb-05f7f584bd93)

I get a `FWHM` in a range of approximately 3-4 px if I choose a range of half of the height of the edge (as in the image, the color of the selections corresponding to the color of the painted circles on the figures).

And with bigger smoothing it also works for a bigger selection:

Small smoothing (the results as it can be seen are not good):

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/3e6063b3-9e4a-4e3c-91e2-e51b7cc2e857)

Bigger smoothing (FWHM is also around 3 px):

![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/50303550/8631140b-c44d-4051-ac8b-2758f36be520)


Finally, I'm not sure why the result you showed above is different from mine, if its due to the different resolution, of course I'll would be glad to converge to the same result, but we may leave it as is, because I'm unaware of the reason of that. 

Just one last question (if the above seems resolved to you as well):

> Again, according to the documentation, the proper smoothing factor will depend on the number of points. In fact, the default value, is a function of the number of points.

Mentioning the documentation, are you talking about the `ISO 12233` standard ? Any particular version of it ? 

I saw for example in the Matlab code of Peter D.Burns that uses another approach of oversampling which is binning data in 4x sampled array, so there is clearly a degree of freedom in different implementations, so I'm curious what documentation you are referring to.

Thank you in advance.

**Comment by JorgeGIlG** [comment]
Hi @ilyak93, thank you for your feedback.
> 
> Finally, I'm not sure why the result you showed above is different from mine, if its due to the different resolution, of course I'll would be glad to converge to the same result, but we may leave it as is, because I'm unaware of the reason of that.

I think I get similar results to yours with the last sample you submitted.

```
jrgg@DMSLP0313:~/desktop$ gdalinfo 287512125-8d4be50b-1d3f-48b8-a0e5-fcb05aeeb99e.png; md5sum 287512125-8d4be50b-1d3f-48b8-a0e5-fcb05aeeb99e.png 
Driver: PNG/Portable Network Graphics
Files: 287512125-8d4be50b-1d3f-48b8-a0e5-fcb05aeeb99e.png
Size is 2560, 1920
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 1920.0)
Upper Right ( 2560.0,    0.0)
Lower Right ( 2560.0, 1920.0)
Center      ( 1280.0,  960.0)
Band 1 Block=2560x1 Type=Byte, ColorInterp=Gray
0302cedbad4f518eb73cdcfcd12ce5e1  287512125-8d4be50b-1d3f-48b8-a0e5-fcb05aeeb99e.png
```
![image](https://github.com/JorgeGIlG/MTF_Estimator/assets/67840250/494efa2b-6f3c-4bb7-9adb-f5d3cbbf80bd)






> 
> Just one last question (if the above seems resolved to you as well):
> 
> > Again, according to the documentation, the proper smoothing factor will depend on the number of points. In fact, the default value, is a function of the number of points.
> 
> Mentioning the documentation, are you talking about the `ISO 12233` standard ? Any particular version of it ?

The last version I reviewed was ISO 12233:2017. I don't think it has changed much, at least in the essentials.

> I saw for example in the Matlab code of Peter D.Burns that uses another approach of oversampling which is binning data in 4x sampled array, so there is clearly a degree of freedom in different implementations, so I'm curious what documentation you are referring to.

I was referring to the [SciPy manual](https://docs.scipy.org/doc/scipy/tutorial/interpolate/smoothing_splines.html).

If you decide to follow the ISO [imatest](https://www.imatest.com/) has software they claim is compliant.

**Comment by ilyak93** [comment]
@JorgeGIlG, that's great. Thanks for the info about the ISO. 

> I was referring to the [SciPy manual](https://docs.scipy.org/doc/scipy/tutorial/interpolate/smoothing_splines.html).

Now I see it.

Generally, thank you for a very fruitful and educational discussion and Q&A, now I am able to compare different approaches through the ISO methodology, particularly the Slanted Edge approach.

**Comment by ilyak93** [comment]
@JorgeGIlG, I cleaned some comments about the new version of the QGIS, it works fine, I just didn't find the right button previously. I think this post is efficient without those. Just you to notice that above.

I'll delete this comment as well afterward.
