### ISSUE TITLE
Is there any problem with this code  diff = y - a + b*x

### ISSUE THREAD

**Issue by Programmerwyl** [JorgeGIlG/MTF_Estimator#9]
I would like to confirm whether there is a problem with this code 
diff = y - a + b*x
and whether it should be changed to
diff = y - （a + b*x）

thanks

**Comment by JorgeGIlG** [comment]
Yes. You are right. Luckily it is in the subpixel outlier removal routine and the bug doesn't have a huge impact. 
I've updated the code and the QGIS plugin. 
Thank you!
